version: '3.8'

services:
  front:
    build: .
    container_name: vue3-vite-docker-kit
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped